# Generated by Django 5.0 on 2023-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_alter_client_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status_try', models.BooleanField(verbose_name='статус попытки')),
                ('server_answer', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('last_try',),
            },
        ),
        migrations.CreateModel(
            name='SendOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(verbose_name='время рассылки')),
                ('send_period', models.CharField(max_length=20, verbose_name='периодичность')),
                ('send_status', models.CharField(max_length=20, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
                'ordering': ('send_time',),
            },
        ),
        migrations.CreateModel(
            name='SendText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_title', models.CharField(max_length=100, verbose_name='тема')),
                ('mail_text', models.TextField(verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('mail_title',),
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('client_name',), 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
    ]
