# Generated by Django 5.0 on 2023-12-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_logs_sendoptions_sendtext_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendoptions',
            name='send_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='наименование рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.CharField(max_length=30, unique=True, verbose_name='контактный email'),
        ),
    ]
