# Generated by Django 5.0 on 2023-12-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_client_send_options_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendoptions',
            name='send_time',
            field=models.TimeField(verbose_name='время рассылки'),
        ),
    ]
