# Generated by Django 5.0 on 2023-12-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_alter_sendoptions_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtext',
            name='send_options_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.sendoptions', verbose_name='наименование рассылки'),
        ),
    ]
