# Generated by Django 5.0 on 2023-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_sendtext_send_options_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendoptions',
            name='mail_text',
            field=models.TextField(default='Добрый день!', verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='mail_title',
            field=models.CharField(default='Сообщение от Invest Store!', max_length=100, verbose_name='тема'),
        ),
        migrations.DeleteModel(
            name='SendText',
        ),
    ]
