# Generated by Django 5.0 on 2023-12-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_sendoptions_mail_text_sendoptions_mail_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendoptions',
            name='client_email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailer.client', verbose_name='контактный email'),
        ),
    ]
