# Generated by Django 5.0 on 2023-12-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0009_sendoptions_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendoptions',
            name='client_email',
            field=models.ForeignKey(default='Не указана', on_delete=django.db.models.deletion.CASCADE, to='mailer.client', verbose_name='контактный email'),
        ),
    ]
