# Generated by Django 5.0 on 2023-12-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0011_alter_sendoptions_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='send_options_name',
        ),
    ]
