# Generated by Django 5.0 on 2023-12-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0012_remove_client_send_options_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendoptions',
            name='send_period',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('RFI/RFD', 'RFI/RFD'), ('...', '...')], default='', max_length=20, verbose_name='периодичность'),
        ),
    ]
