# Generated by Django 5.0 on 2023-12-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0014_alter_sendoptions_send_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendoptions',
            name='send_period',
            field=models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='', max_length=20, verbose_name='периодичность'),
        ),
    ]
