# Generated by Django 5.0 on 2023-12-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0015_alter_sendoptions_send_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendoptions',
            name='send_status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='', max_length=20, verbose_name='статус рассылки'),
        ),
    ]
