# Generated by Django 5.0 on 2023-12-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0016_alter_sendoptions_send_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='тема письма')),
                ('text', models.TextField(verbose_name='текст письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AlterModelOptions(
            name='sendoptions',
            options={'ordering': ('send_start',), 'verbose_name': 'настройка', 'verbose_name_plural': 'настройки'},
        ),
        migrations.RemoveField(
            model_name='sendoptions',
            name='mail_title',
        ),
        migrations.RemoveField(
            model_name='sendoptions',
            name='send_time',
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='send_finish',
            field=models.DateTimeField(default=None, verbose_name='время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='send_next_try',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время попытки'),
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='send_start',
            field=models.DateTimeField(default=None, verbose_name='время начала рассылки'),
        ),
        migrations.RemoveField(
            model_name='sendoptions',
            name='client_email',
        ),
        migrations.AlterField(
            model_name='sendoptions',
            name='send_name',
            field=models.CharField(default=None, max_length=200, verbose_name='наименование рассылки'),
        ),
        migrations.AlterField(
            model_name='sendoptions',
            name='mail_text',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailer.message', verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='client_email',
            field=models.ManyToManyField(to='mailer.client', verbose_name='контактный email'),
        ),
    ]
