# Generated by Django 5.0 on 2023-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0017_message_alter_sendoptions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.CharField(max_length=150, unique=True, verbose_name='контактный email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
    ]
