# Generated by Django 5.0 on 2023-12-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0018_alter_client_client_email_alter_client_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='тема письма'),
        ),
    ]
