# Generated by Django 5.0 on 2023-12-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0019_alter_message_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendoptions',
            name='mail_text',
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='mail_title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailer.message', verbose_name='тема рассылки'),
        ),
    ]
