# Generated by Django 5.0 on 2023-12-17 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0020_remove_sendoptions_mail_text_sendoptions_mail_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendoptions',
            name='client_email',
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='client_email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mailer.client', verbose_name='контактный email'),
        ),
    ]
