# Generated by Django 4.2.4 on 2023-12-22 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0022_sendoptions_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendoptions',
            old_name='owner',
            new_name='options_owner',
        ),
        migrations.AddField(
            model_name='client',
            name='client_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
