# Generated by Django 4.2.4 on 2023-12-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0024_alter_logs_status_try'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ('-last_try',), 'verbose_name': 'лог', 'verbose_name_plural': 'логи'},
        ),
    ]
