# Generated by Django 4.2.4 on 2023-12-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0026_logs_send_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='server_answer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='ответ сервера'),
        ),
    ]
