# Generated by Django 4.2.4 on 2023-12-27 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0027_alter_logs_server_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='client_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='send_name',
            field=models.CharField(default=None, max_length=200, verbose_name='наименование рассылки'),
        ),
    ]
