# Generated by Django 4.2.4 on 2023-12-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0028_logs_client_owner_alter_logs_send_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='client_owner',
            new_name='logs_owner',
        ),
        migrations.AddField(
            model_name='message',
            name='message_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
