# Generated by Django 4.2.4 on 2023-12-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0029_rename_client_owner_logs_logs_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendoptions',
            name='client_email',
        ),
        migrations.AlterField(
            model_name='sendoptions',
            name='send_status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=20, verbose_name='статус рассылки'),
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='client_email',
            field=models.ManyToManyField(to='mailer.client', verbose_name='контактный email'),
        ),
    ]
