# Generated by Django 4.2.4 on 2023-12-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0030_remove_sendoptions_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendoptions',
            name='send_next_try',
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='interval_try',
            field=models.IntegerField(blank=True, null=True, verbose_name='интервал попытки (дни)'),
        ),
    ]
