# Generated by Django 4.2.4 on 2023-12-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0031_remove_sendoptions_send_next_try_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='send_email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='почта отправки'),
        ),
    ]
