# Generated by Django 4.2.4 on 2023-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0032_logs_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendoptions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность'),
        ),
    ]
