# Generated by Django 4.2.4 on 2024-01-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0033_sendoptions_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendoptions',
            name='interval_try',
        ),
        migrations.AddField(
            model_name='sendoptions',
            name='next_try',
            field=models.DateTimeField(blank=True, null=True, verbose_name='следующая попытка'),
        ),
    ]
