# Generated by Django 4.2.4 on 2024-01-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0034_remove_sendoptions_interval_try_sendoptions_next_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendoptions',
            name='next_try',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='следующая попытка'),
        ),
    ]
