# Generated by Django 4.2.4 on 2024-01-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0037_alter_sendoptions_next_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendoptions',
            name='next_try',
            field=models.DateTimeField(blank=True, null=True, verbose_name='следующая попытка'),
        ),
    ]
