# Generated by Django 5.0 on 2023-12-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verification_code_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='15714303', max_length=8, null=True, verbose_name='код подтверждения почты'),
        ),
    ]
