# Generated by Django 5.0 on 2023-12-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='86908779', max_length=8, null=True, verbose_name='код подтверждения почты'),
        ),
    ]
