# Generated by Django 4.2.4 on 2023-12-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_is_active_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='14153043', max_length=8, null=True, verbose_name='код подтверждения почты'),
        ),
    ]
