# Generated by Django 4.2.4 on 2023-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='95424945', max_length=8, null=True, verbose_name='код подтверждения почты'),
        ),
    ]
