# Generated by Django 4.2.4 on 2024-01-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='44987999', max_length=8, null=True, verbose_name='код подтверждения почты'),
        ),
    ]
