version: "3.9"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mailing_service
    env_file:
      - .env

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mailing_service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    tty: true
    command: >
      bash -c "python manage.py makemigrations 
      && python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - mailing_service
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:

networks:
  mailing_service:
    driver: bridge